### ISSUE TITLE
Support automatic backup

### ISSUE THREAD

**Issue by colaorange** [colaorange/daily-money-one-doc#3]

**Comment by dennischen** [comment]
Enable it in `Data Maintenance`
<img src="https://github.com/colaorange/daily-money-one-doc/assets/788787/72ed28cc-69e1-49f5-88f3-d4cfa698f75f" width="400"/>

Configure it in `Data Maintenance > Automatic Database Backup`
<img src="https://github.com/colaorange/daily-money-one-doc/assets/788787/b860b8e3-54eb-41f7-bb6b-c86402df7beb" width="400"/>
