### ISSUE TITLE
Error adding some advance entry 

### ISSUE THREAD

**Issue by max-matty** [colaorange/daily-money-one-doc#73]
Random error adding an advance entry.

Example: 
- Transfer-out Amount 512.59
- Transfer-in Amount 512.03
- Transfer-in Amount 0.56

Return the following error:
Total transfer-out amount 512.59 is not equal to total transfer-in amount 512.58999999999

And made impossible for me to add the transaction.
Any help appreciated.

**Comment by dennischen** [comment]
it is a bug. I plan to release version 1.6.0 soon and will aim to fix it in that release

**Comment by dennischen** [comment]
@max-matty 
Did you receive an email from colo.orange@gmail.com around August 27, 2024? The subject is "About Daily Money One no-ads." Could you please check your inbox or trash folder for it?
Thank you again for your donation!

**Comment by max-matty** [comment]
@dennischen 
Sorry I can't find the email.
Maybe it was permanently deleted by the system (email older than 30 days in trash/spam folder are).
Can you please send it again?
Thanks.

**Comment by dennischen** [comment]
@max-matty 
Sent, please check again

**Comment by max-matty** [comment]
@dennischen 
I've just replayed to your email.

**Comment by dennischen** [comment]
Fixed in 1.6.0: In advanced mode, when withdrawing and depositing within the same book and checking value equations, the editor will perform the check based on the book's fraction digits and rounded values.

**Comment by max-matty** [comment]
I've just received the update.
Now everything is ok!!!
👍

Massimo Fontana
PEC: ***@***.***

Il dom 6 ott 2024, 15:19 Dennis Chen ***@***.***> ha scritto:
